// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/log-workout-set.ts
import { createClient } from "npm:@supabase/supabase-js@^2.48.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var CATEGORIES = [
  "\u03A3\u03A4\u0397\u0398\u039F\u03A3",
  "\u03A0\u039B\u0391\u03A4\u0397",
  "\u0394\u0399\u039A\u0395\u03A6\u0391\u039B\u0391",
  "\u03A4\u03A1\u0399\u039A\u0395\u03A6\u0391\u039B\u0391",
  "\u03A9\u039C\u039F\u0399",
  "\u03A0\u039F\u0394\u0399\u0391",
  "\u039A\u039F\u03A1\u039C\u039F\u03A3",
  "CARDIO",
  "POWER SETS"
];
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_workout_set_default = defineTool({
  name: "log_workout_set",
  title: "Log a workout set",
  description: "Log a single workout set for the signed-in user. Provide the exercise name (uppercase, no accents), one of the fixed Greek category codes (e.g. \u03A3\u03A4\u0397\u0398\u039F\u03A3, \u03A0\u039B\u0391\u03A4\u0397, \u03A0\u039F\u0394\u0399\u0391), the set number, weight in kg, and reps.",
  inputSchema: {
    exercise_name: z.string().trim().min(1).describe("Exercise name, e.g. 'BENCH PRESS'."),
    category: z.enum(CATEGORIES).describe("Muscle-group category (Greek code)."),
    set_number: z.number().int().min(1).max(50),
    weight_kg: z.number().min(0).max(1e3),
    reps: z.number().int().min(0).max(500),
    workout_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date in YYYY-MM-DD. Defaults to today (UTC) if omitted.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: existing } = await sb.from("exercises").select("id, name").ilike("name", args.exercise_name).eq("category", args.category).maybeSingle();
    const insertRow = {
      user_id: ctx.getUserId(),
      category: args.category,
      set_number: args.set_number,
      weight_kg: args.weight_kg,
      reps: args.reps,
      workout_date: args.workout_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      exercise_id: existing?.id ?? null,
      custom_exercise: existing ? null : args.exercise_name.toUpperCase()
    };
    const { data, error } = await sb.from("workout_logs").insert(insertRow).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Logged set #${data.set_number} of ${args.exercise_name}: ${data.weight_kg}kg x ${data.reps}` }],
      structuredContent: { row: data }
    };
  }
});

// src/lib/mcp/tools/list-recent-workouts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.48.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_workouts_default = defineTool2({
  name: "list_recent_workouts",
  title: "List recent workouts",
  description: "List the signed-in user's most recent workout sets, newest first. Each row is one logged set (exercise, category, weight in kg, reps, set number, date).",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).default(50).describe("Maximum number of sets to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("workout_logs").select("id, workout_date, category, custom_exercise, exercise_id, set_number, weight_kg, reps, exercises(name)").eq("user_id", ctx.getUserId()).order("workout_date", { ascending: false }).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = (data ?? []).map((r) => ({
      id: r.id,
      date: r.workout_date,
      category: r.category,
      exercise: r.custom_exercise ?? r.exercises?.name ?? "Unknown",
      set_number: r.set_number,
      weight_kg: r.weight_kg,
      reps: r.reps
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { rows }
    };
  }
});

// src/lib/mcp/tools/get-workout-stats.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.48.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_workout_stats_default = defineTool3({
  name: "get_workout_stats",
  title: "Get workout stats",
  description: "Return summary stats for the signed-in user over the last N days: total sets, total volume (kg*reps), unique training days, and per-category volume breakdown.",
  inputSchema: {
    days: z3.number().int().min(1).max(365).default(30).describe("Look-back window in days.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const since = new Date(Date.now() - days * 24 * 60 * 60 * 1e3).toISOString().slice(0, 10);
    const { data, error } = await sb.from("workout_logs").select("workout_date, category, weight_kg, reps").eq("user_id", ctx.getUserId()).gte("workout_date", since);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    const days_set = /* @__PURE__ */ new Set();
    const byCategory = {};
    let totalVolume = 0;
    for (const r of rows) {
      days_set.add(r.workout_date);
      const vol = (r.weight_kg ?? 0) * (r.reps ?? 0);
      totalVolume += vol;
      byCategory[r.category] = (byCategory[r.category] ?? 0) + vol;
    }
    const stats = {
      window_days: days,
      total_sets: rows.length,
      total_volume_kg: Math.round(totalVolume),
      training_days: days_set.size,
      volume_by_category: byCategory
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/tools/list-templates.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.48.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_templates_default = defineTool4({
  name: "list_workout_templates",
  title: "List workout templates",
  description: "List the signed-in user's saved workout templates with their exercises.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const { data, error } = await sb.from("workout_templates").select("id, name, description, exercises, updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { templates: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ygjzljotnkjadiolbiwk";
var mcp_default = defineMcp({
  name: "fittrack-mcp",
  title: "FitTrack MCP",
  version: "0.1.0",
  instructions: "Tools for the FitTrack fitness tracker. Use `log_workout_set` to add a set, `list_recent_workouts` to see recent sets, `get_workout_stats` for a volume summary, and `list_workout_templates` to see saved templates. Category values are fixed Greek codes (\u03A3\u03A4\u0397\u0398\u039F\u03A3, \u03A0\u039B\u0391\u03A4\u0397, \u0394\u0399\u039A\u0395\u03A6\u0391\u039B\u0391, \u03A4\u03A1\u0399\u039A\u0395\u03A6\u0391\u039B\u0391, \u03A9\u039C\u039F\u0399, \u03A0\u039F\u0394\u0399\u0391, \u039A\u039F\u03A1\u039C\u039F\u03A3, CARDIO, POWER SETS). Exercise names are uppercase without accents.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [log_workout_set_default, list_recent_workouts_default, get_workout_stats_default, list_templates_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
