
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygjzljotnkjadiolbiwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlnanpsam90bmtqYWRpb2xiaXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1Mjg1NTgsImV4cCI6MjA1NTEwNDU1OH0.5gUnW1YIlFSOLucV0f5aRQrwbFyPxjCAJqHDp-_WJEs";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    }
  }
);
